### ISSUE TITLE
Last version not works under windows

### ISSUE THREAD

**Issue by zdm** [mhinz/vim-signify#228] opened 2017-02-19 00:03 UTC
Seems, that vcs couldn't be detected properly.

SignifyDebug output:
![screenshot 2017-02-19 02 01 20](https://cloud.githubusercontent.com/assets/1025608/23097818/86284806-f647-11e6-9af5-5009cdf7675b.png)

SignifyList output:
![screenshot 2017-02-19 02 01 31](https://cloud.githubusercontent.com/assets/1025608/23097822/a29a0132-f647-11e6-8ddb-bafab6cfc18d.png)

**Comment by zdm** [comment] 2017-02-19 00:04
Under linux everything works fine.

**Comment by mhinz** [comment] 2017-02-19 00:34
Yea, I have an idea why it happens. It's a race condition when Sy is run twice.

Try opening the file with `vim -V1 file`. Afterwards check `:messages`. It probably contains a line: `No VCS found. Disabling.`, right?

**Comment by zdm** [comment] 2017-02-19 00:41
Hmm, no.
I don;t see any lines related to VCS or Signify in :mess output

**Comment by zdm** [comment] 2017-02-19 00:42
...
No mapping found
[sy] Register new file.
[sy:hg] get_diff_start()
[sy:git] get_diff_start()
...

That's all, signs are not displayed.

**Comment by mhinz** [comment] 2017-02-19 00:48
Well, I meant `vim -V1 Server.pm` in that case, or any other file managed by either Hg or Git. Then `:messages` should contain more lines starting with `[sy...`

**Comment by zdm** [comment] 2017-02-19 00:51
Yes, I understood what you mean.

Here is full :mess output

```
not found in 'runtimepath': "bitmaps/vim.ico"
could not source "$VIM\vimrc"
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
not found in 'runtimepath': "plugin/**/*.vim"
Reading viminfo file "C:/Users/zdm/.vim/.viminfo" info oldfiles
"License.pm" [unix] 120L, 4257C
Reading viminfo file "C:/Users/zdm/.vim/.viminfo" marks
Reading undo file:
C:/Users/zdm/.vim/undo\d%%projects%lazarus-crawler-server%lib%Lazarus%Crawler%Server%License.pm
No mapping found
No mapping found
No mapping found
No mapping found
No mapping found
No mapping found
No mapping found
No mapping found
...
No mapping found
No mapping found
[sy] Register new file.
[sy:hg] get_diff_start()
[sy:git] get_diff_start()
```

**Comment by zdm** [comment] 2017-02-19 01:21
also, maybe this will be useful.

It is better to use "chg" instead of "hg". This command is available in
the latest mercurial 4.1.0 and transparently replaces hg.

Chg is a C client for standalone hg server, so it is really faster, than
python hg.

So, you can check for chg first and use it instead of hg, if it is
available.

**Comment by mhinz** [comment] 2017-02-19 01:24
Hmm, so the jobs never even return, otherwise you'd get messages like `[sy:hg] callback_exit()` and `[sy:git] callback_exit()`.

Please update Sy and do the `-V1`/`:messages` dance again. It should now also output the exact command about to get run and the current working directory.

**Comment by zdm** [comment] 2017-02-19 01:26
did you commit something?
i updated, but no changes were found.

**Comment by mhinz** [comment] 2017-02-19 01:32
*cough* Please try again. :)

**Comment by zdm** [comment] 2017-02-19 01:35
Signs not displayed, here is the :mess output:

```
...
No mapping found
[sy] Register new file.
[sy:hg] get_diff_start()
[sy:hg] CMD: 'hg diff --config extensions.color=! --config
defaults.diff= --nodates -U0 --
"d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\Lice
nse.pm"' | CWD:
d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server
[sy:git] get_diff_start()
[sy:git] CMD: 'git diff --no-color --no-ext-diff -U0 -- "License.pm"' |
CWD: d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server
```

**Comment by mhinz** [comment] 2017-02-19 01:39
Is running this manually working?

```
:!hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"
```

**Comment by zdm** [comment] 2017-02-19 01:45
no.

:!hg diff --config extensions.color=! --config defaults.diff= --nodates
-U0 --
"d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm

E34: no previous command

**Comment by mhinz** [comment] 2017-02-19 01:49
Hmm, and this?

```
!hg diff --config extensions.color=\! --config defaults.diff= --nodates -U0 -- "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"
```

**Comment by zdm** [comment] 2017-02-19 01:51
yes, this works and print diff in the new console window.

**Comment by mhinz** [comment] 2017-02-19 02:07
Okay, put this in a file `test.vim`:

```viml
function! s:stdout(id, data)
  echomsg string(a:data)
endfunction

function! s:stderr(id, data)
  echomsg 'ERROR: '. string(a:data)
endfunction

let s:cmd = 'hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'

call job_start(s:cmd, {
      \ 'in_io': 'null',
      \ 'out_cb': function('s:stdout'),
      \ 'err_cb': function('s:stderr')
      \ })
```

Now open that file with `vim -S test.vim`. What's the output of `:messages`?

**Comment by zdm** [comment] 2017-02-19 02:11
:mess is empty

**Comment by mhinz** [comment] 2017-02-19 02:19
What about this?

```viml
function! s:stdout(id, data)
  echomsg string(a:data)
endfunction

function! s:stderr(id, data)
  echomsg 'ERROR: '. string(a:data)
endfunction

let s:cmd = 'hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'

call job_start(shellescape(s:cmd), {
      \ 'in_io': 'null',
      \ 'out_cb': function('s:stdout'),
      \ 'err_cb': function('s:stderr')
      \ })
```

(Mind the added `shellescape()`.)

**Comment by zdm** [comment] 2017-02-19 02:25
still empty

i added echomsg 'START...' and see this message, but your function
doesn't print anything.

**Comment by jamessan** [comment] 2017-02-19 02:28
No, you don't `shellescape` an entire command.  `shellescape` is for a single argument within a command.  Try

```vim
let s:cmd = 'hg diff --config ' . shellescape('extensions.color=!'). ' --config defaults.diff= --nodates -U0 -- "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'
```

or even better (hopefully):

```vim
let s:cmd = ['hg', 'diff', '--config', 'extensions.color=!', '--config', 'defaults.diff=', '--nodates', '-U0', '--', 'd:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm']
```

**Comment by mhinz** [comment] 2017-02-19 02:28
The help says that a string works better for Win.

**Comment by zdm** [comment] 2017-02-19 02:34
I tried.

this returns nothing:
let s:cmd = 'hg diff --config ' . shellescape('extensions.color=!'). '
--config defaults.diff= --nodates -U0 --
"d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'



this returns error - using list as string
let s:cmd = ['hg', 'diff', '--config', 'extensions.color=!', '--config',
'defaults.diff=', '--nodates', '-U0', '--',
'd:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm']

**Comment by mhinz** [comment] 2017-02-19 02:38
Maybe...

```viml
function! s:stdout(id, data)
  echomsg string(a:data)
endfunction

function! s:stderr(id, data)
  echomsg 'ERROR: '. string(a:data)
endfunction

function! s:exit(id, exitval)
  echomsg 'EXITVAL: '. a:exitval
endfunction

let s:cmd = 'hg diff "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'

call job_start(s:cmd, {
      \ 'in_io':   'null',
      \ 'out_cb':  function('s:stdout'),
      \ 'err_cb':  function('s:stderr'),
      \ 'exit_cb': function('s:stderr'),
      \ })
```

**Comment by mhinz** [comment] 2017-02-19 02:39
Maybe..

```viml
function! s:stdout(id, data)
  echomsg string(a:data)
endfunction

function! s:stderr(id, data)
  echomsg 'ERROR: '. string(a:data)
endfunction

function! s:exit(id, exitval)
  echomsg 'EXITVAL: '. a:exitval
endfunction

let s:cmd = 'hg diff "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'

call job_start(s:cmd, {
      \ 'in_io':   'null',
      \ 'out_cb':  function('s:stdout'),
      \ 'err_cb':  function('s:stderr'),
      \ 'exit_cb': function('s:exit'),
      \ })
```

**Comment by zdm** [comment] 2017-02-19 02:46
no output

i tried let s:cmd = 'dir
d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server'

it works and print dir content to mess

**Comment by mhinz** [comment] 2017-02-19 02:48
So the double quotes are the issue?

```
let s:cmd = 'hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm'
```

**Comment by zdm** [comment] 2017-02-19 02:49
let s:cmd = 'hg help'

also not works.

something with redirecting hg output?

**Comment by zdm** [comment] 2017-02-19 02:50
let s:cmd = 'git --help'

also not works

**Comment by zdm** [comment] 2017-02-19 02:52
let s:cmd = 'netstat /?' - works

**Comment by mhinz** [comment] 2017-02-19 02:58
Maybe...

```
let s:cmd = 'start /b hg help'
```

**Comment by zdm** [comment] 2017-02-19 02:58
seems, that ENV PATH is not inherited

let s:cmd = 'd:\devel\hg\hg.exe help' - works

**Comment by zdm** [comment] 2017-02-19 03:00
start /b - not works

**Comment by zdm** [comment] 2017-02-19 03:02
ok, i tried full path to hg

let s:cmd = 'd:\devel\hg\hg.exe diff --config extensions.color=!
--config defaults.diff= --nodates -U0
d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm'

it works and return diff

**Comment by mhinz** [comment] 2017-02-19 03:13
Hmm, but why would `:!` work without the absolute path?

I need to sleep over this and try to get access to Windows tomorrow. ;-)

**Comment by zdm** [comment] 2017-02-19 03:15
hmm, i don;t know, but:

:! - inherit ENV variables, but
job_start() - not,

ok, i am also going to bad, let's talk tomorrow
good night

**Comment by mhinz** [comment] 2017-02-19 12:06
Okay, after a good night's sleep the docs (`:h job_start()`) seem to be very clear about it:

```
The command is executed directly, not through a shell, the 'shell' option is not used. 

On Unix $PATH is used to search for the executable only when the command does
not contain a slash.
```

Neovim basically does this:

```viml
function! s:stdout(id, data)
  echomsg string(a:data)
endfunction

function! s:stderr(id, data)
  echomsg 'ERROR: '. string(a:data)
endfunction

function! s:exit(id, exitval)
  echomsg 'EXITVAL: '. a:exitval
endfunction

let s:cmd = 'hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'

let s:foo = join([&shell, &shellcmdflag, s:cmd])
" let s:foo = join([&shell, &shellcmdflag, shellescape(s:cmd)])

call job_start(s:foo, {
      \ 'in_io':   'null',
      \ 'out_cb':  function('s:stdout'),
      \ 'err_cb':  function('s:stderr'),
      \ 'exit_cb': function('s:exit'),
      \ })
```

**Comment by zdm** [comment] 2017-02-19 12:58
I tested latest code.
It returns only cmd exit code (0) but not hg diff output.

**Comment by mhinz** [comment] 2017-02-19 13:24
Okay, small steps.. `let s:cmd = 'hg help'`?

**Comment by zdm** [comment] 2017-02-19 13:28
works, returns complete hg help.

i need to go, will be available again in 2 hours.

**Comment by mhinz** [comment] 2017-02-19 13:39
Okay, cool. Then let's try these in order until it breaks:

1. Without double quotes:
    ```
    let s:cmd = 'hg diff d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm'
   ```
1. With double quotes:
   ```
   let s:cmd = 'hg diff "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'
   ```
1. With double-dash:
   ```
   let s:cmd = ''hg diff -- "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'
   ```

**Comment by zdm** [comment] 2017-02-19 13:50
1. returns only shell exit code;
2. returns only shell exit code;
3. script error, error in let expression;

**Comment by mhinz** [comment] 2017-02-19 13:53
Yea, you use mails you don't see when people edit their Github posts. I fixed 3. after posting.

But I have no idea why not even 1. is working. Are you sure the file currently has changes? Can you play around with the path until it works?

**Comment by zdm** [comment] 2017-02-19 13:56
Oh, shit. Sorry, license.pm was updated and commited since yesterday.

1 and 2 works perfectly.

**Comment by mhinz** [comment] 2017-02-19 13:59
Oh, that's good!

So, how about:

```
let s:cmd = 'hg diff -- "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'
```

and then everything:

```
let s:cmd = 'hg diff --config extensions.color=! --config defaults.diff= --nodates -U0 -- "d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\License.pm"'
```

**Comment by zdm** [comment] 2017-02-19 14:03
both works

**Comment by mhinz** [comment] 2017-02-19 14:07
Awesome. Then the whole issue is about not using an absolute path and we can work around that using the values of `:h 'shell'` and `:h 'shellcmdflag'`.

**Comment by mhinz** [comment] 2017-02-19 14:18
Okay, one last test.. I just want to confirm that `job_start()` on Win throws an error when a list is passed..

```
let s:cmd = ['hg', 'diff']
```

**Comment by zdm** [comment] 2017-02-19 14:35
yes, this code throw error.

**Comment by mhinz** [comment] 2017-02-19 16:12
Okay, please update Sy and see if it works.

**Comment by zdm** [comment] 2017-02-19 16:29
Yes, it works, thank you very much.

But something wrong with behavior under windows.
Give me 5 minutes, I will try to describe it here.

**Comment by zdm** [comment] 2017-02-19 16:40
so, I am using:

latest vim 8.0.0341 x64 under linux and windows.

```
let g:signify_vcs_list = [ 'hg', 'git' ]
let g:signify_realtime = 1
```
Following issues described for windows version. Under linux everything works as expected.

1. when I am opening file, that has already changes - signs are not displayed. Only displayed after buffer was changed in vim and saved;

Only single issue so far ;-)

**Comment by zdm** [comment] 2017-02-19 17:03
And the second issue:

For some files it do not works at all.
For example, i am opened two .pm files from the same directory.
For first file it works and shows signs, but for second not works at all.

**Comment by mhinz** [comment] 2017-02-19 17:07
Man, Windows is doing me in..

What was the exact command you used to open the two files? Is `:messages` showing anything suspicious when using `vim -V1`?

**Comment by zdm** [comment] 2017-02-19 18:27
So, i found the strange behavior.

Wen I run gvim -V1 file.txt

- vim started and show different messages;
- signify started and print log;
- signify shows signs;
- after this vim print message "Press ENTER or type command to continue";
- signs disappears after I press ENTER;

**Comment by mhinz** [comment] 2017-02-19 18:34
So, what's the actual output of `:messages`?

**Comment by zdm** [comment] 2017-02-19 18:37
```
...
No mapping found
No mapping found
[sy] Register new file.
[sy:hg] get_diff_start()
[sy:hg] CMD: 'C:\Windows\system32\cmd.exe /c hg diff --config
extensions.color=! --config defaults.diff= --nodates -U0 --
"d:\projects\lazarus-crawler-server\
lib\Lazarus\Crawler\Server\Market\API\V1\Market.pm"' | CWD:
d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\Market\API\V1
[sy:git] get_diff_start()
[sy:git] CMD: 'C:\Windows\system32\cmd.exe /c git diff --no-color
--no-ext-diff -U0 -- "Market.pm"' | CWD:
d:\projects\lazarus-crawler-server\lib\Lazarus\Crawler\Server\Market\API\V1
[sy:git] callback_exit()
[sy:git] get_diff_git()
[sy:git] get_diff_end()
[sy:hg] callback_exit()
[sy:hg] get_diff_hg()
[sy:hg] get_diff_end()
[sy:hg] set_signs()
Press ENTER or type command to continue
```

**Comment by mhinz** [comment] 2017-02-19 19:21
Hard to say. The output looks good and it tries to set the signs at least. And since there's no message `[sy:hg] No changes found.`, it also means it found a diff.

Can you try the same with vim in cmd.exe directly? I bet it works and the issue only happens in gVim.

**Comment by zdm** [comment] 2017-02-19 19:38
Yes, you are right.
In console vim everything is ok.

**Comment by mhinz** [comment] 2017-02-19 20:07
Someone mentioned a similar issue with MacVim before. I think that's just how each GUI works and there's nothing I can do about it from this plugin. :\

When I'm not mistaken, the signs actually get defined, but the GUI doesn't show them until a certain point where the screen is redrawn. E.g. when gVim is showing no signs, what's the output of `:sign place`? It should list all placed signs.

**Comment by zdm** [comment] 2017-02-19 20:48
"sign places" shows nothing when no signs are displayed.

seems, that i found a problem. this is possible error in xkbswitch plugin.
testing...

**Comment by mhinz** [comment] 2017-02-20 00:45
Okay, the above commit should make sign updates in GUIs a bit smoother.

I can reproduce the "no signs at start" issue in MacVim and try to resolve it at the moment.

**Comment by mhinz** [comment] 2017-02-20 02:45
Okay, the issue is that the exit handler is run _before_ the stdout handler. Vim doesn't guarantee any order here. I'll look into synchronizing the callbacks manually.

**Comment by zdm** [comment] 2017-02-20 02:47
Thank you very much for your work.
Tell me, if you need some help.

**Comment by mhinz** [comment] 2017-02-20 13:53
Please update and try again in gVim.

At least for MacVim I fixed all the bugs that I could reproduce.

**Comment by mhinz** [comment] 2017-02-20 14:50
Since the actual Windows bug is solved, I'm closing this. Thanks for reporting this and all the feedback so far.

---

Anyway, let's continue using this tread for making sure the GUI bugs are straightened out.

**Closed by mhinz** 2017-02-20 14:50 UTC

**Comment by zdm** [comment] 2017-02-20 15:32
Hi.

Hmm, new critical issue appears: plugin add ^L to buffer each second.
I can't edit text ;-)

**Comment by zdm** [comment] 2017-02-20 15:34
Please, revert last changes.

**Comment by zdm** [comment] 2017-02-20 15:46
Also, just discovered, that with let g:signify_realtime = 1 it save
original file and, than, makes diff.

I thought, that it save a copy in temp dir.

Saving original file may be unwanted in some cases.

**Comment by mhinz** [comment] 2017-02-20 15:49
Please update.

> Also, just discovered, that with let g:signify_realtime = 1 it save
original file and, than, makes diff.

Not sure what you mean. When does it happen?

**Comment by zdm** [comment] 2017-02-20 16:00
Currently it happens periodically, every several seconds, when signify
trying to update diff automatically.

After last update it not happen anymore and let g:signify_realtime = 1
option is not work on windows.

**Comment by mhinz** [comment] 2017-02-20 16:05
1. What does "not work" mean?
2. I guess it only doesn't work in the GUI again?

**Comment by zdm** [comment] 2017-02-20 16:12
1. this means, that diff status not updated automatically, wuth
g:signify_realtime enabled;

2. no, now it doesn't work in console too;

**Comment by mhinz** [comment] 2017-02-20 16:20
Yea, because the cursorhold options were removed. If you put `set autowrite` in your vimrc, it will update automatically now:

https://github.com/mhinz/vim-signify/blob/master/doc/signify.txt#L76-L77

**Comment by mhinz** [comment] 2017-02-20 16:21
The reasoning is that the plugin should never write the buffer on its own. It only does so if the user explicitly wants it by setting 'autowrite'`.

**Comment by mhinz** [comment] 2017-02-20 18:13
Personally tested so far:

- [x] **OSX**: Vim, Neovim, MacVim
- [x] **Linux**: Vim, gVim
- [ ] **Windows**: Vim and gVim

Next step: Install Windows 10 in VirtualBox..

**Comment by zdm** [comment] 2017-02-20 19:02
you are persistent person. ;-)

thank you again for your work.

**Comment by mhinz** [comment] 2017-02-21 18:51
Okay, so I played a bit around with Windows. On `:w`, I always get the updated signs as expected. 

Most of the time the signs get shown at start as well. But sometimes, they don't. Then I have to hit any key, because that redraws the screen and makes the signs show up. It's race condition that I can only reproduce with gVim on Windows. Unfortunately I haven't found a perfect solution for it yet.

Do you see the same issue?

**Comment by zdm** [comment] 2017-02-21 19:58
Seems, that it works for me too.
I don't need to press a key, signs are always displayed.

Will signs update on idle cursor works? Or you decided to disable this
feature?

**Comment by mhinz** [comment] 2017-02-21 21:10
> Will signs update on idle cursor works? Or you decided to disable this
feature?

This works by default, if you do `:set autowrite`.

And I can reproduce the problem now:

```vim
set updatetime=0
set guicursor=a:blinkoff0

sign define A text=AA texthl=ErrorMsg

function! s:set_sign(_id, _exitval)
  execute 'sign place 1 line=1 name=A buffer='. bufnr('')
endfunction

autocmd BufEnter * call job_start('sleep 1', { 'exit_cb': function('s:set_sign') })

edit foo
```

Open this file and run `:so %`. The sign will appear after ~1s. Then uncomment that one line and try again. The sign won't appear as long as you don't hit any key.

Can you confirm that?

**Comment by mhinz** [comment] 2017-02-21 21:12
(In case you didn't see it in the mail, the second line should have been commented out.)

**Comment by zdm** [comment] 2017-02-21 22:09
Yes, everything is like you described.

**Comment by mhinz** [comment] 2017-02-24 17:18
Okay, by now I can't reproduce any races with MacVim or gVim (Linux and Win) anymore. As far as I'm concerned, everything is working as expected with the new asynchronous execution!

Thanks for your feedback!

**Comment by zdm** [comment] 2017-02-24 17:21
Thank you!
