### ISSUE TITLE
How to stage a hunk?

### ISSUE THREAD

**Issue by aganm** [mhinz/vim-signify#332] opened 2020-03-07 04:34 UTC
I can't find how to stage a hunk in the manual. I thought there would be a function called SignifyStageHunk but no luck. How do I do that with signify?

**Comment by cumulotimbus** [comment] 2020-04-15 16:21
See https://github.com/mhinz/vim-signify/issues/119.

tl;dr not gonna happen. 😞

**Comment by timbedard** [comment] 2020-04-15 19:02
See https://github.com/mhinz/vim-signify/issues/119.

**Comment by nomasprime** [comment] 2020-09-20 12:51
Thought about this too and, while it seems convenient, it's a lot of extra functionality to add and maintain across multiple interfaces.

Personally think there's more value in accessing non-editor related functionality directly most of the time anyway. The only exception these days is `Gdiff` but might even pull that out.

**Comment by jamessan** [comment] 2020-09-20 14:00
Duplicate of #119

**Closed by jamessan** 2020-09-20 14:00 UTC
