### ISSUE TITLE
Error with CVS files: get_diff_cvs

### ISSUE THREAD

**Issue by mathomp4** [mhinz/vim-signify#216] opened 2017-02-10 16:29 UTC
All,

I recently did a PluginUpdate and after doing so, I now get this:
```
"MAPL_HistoryGridComp.F90" 4729L, 177910C
Error detected while processing function sy#start..sy#repo#detect..sy#repo#get_diff_start..sy#repo#get_diff_cvs:
line    6:
E706: Variable type mismatch for: diff
```
This is with Vim 7.4, but the cluster I'm on also has Vim 8.0 installed. When I load that module, the error goes away...huzzah! But, I no longer see any signs in the gutter when editing files with changes vs CVS. And the file I'm editing is definitely far from what's checked in (fun with print-statement debugging since I'm running on ~5000 cores!):

```
(1253) $ cvsdiff -l 
Index: MAPL_HistoryGridComp.F90
===================================================================
RCS file: /cvsroot/esma/esma/src/Shared/GEOS_Base/MAPL_HistoryGridComp.F90,v
retrieving revision 1.72.2.2.2.1
diff -b -u -p -r1.72.2.2.2.1 MAPL_HistoryGridComp.F90
--- MAPL_HistoryGridComp.F90	17 Dec 2016 16:32:58 -0000	1.72.2.2.2.1
+++ MAPL_HistoryGridComp.F90	10 Feb 2017 16:28:46 -0000
@@ -674,6 +674,13 @@ contains
 
        string = trim( list(n)%collection ) // '.'
 
+       if (MAPL_AM_I_ROOT()) then
+          write (*,*) "MATMAT: ", trim(string)
+       endif
+
+       call ESMF_VMbarrier(vm, RC=status)
+       VERIFY_(STATUS)
+
        if (trim(list(n)%filename) == "/dev/null") then
           list(n)%disabled = .true.
        else
@@ -945,11 +952,17 @@ contains
        len = ESMF_ConfigGetLen( cfg, label=trim(trim(string) // 'levels:'), rc = status )
 
        LEVS: if( status == ESMF_SUCCESS ) then
-          call ESMF_ConfigFindLabel( config, label=trim(trim(string) // 'levels:'), rc = status )
+          call ESMF_ConfigFindLabel( cfg, label=trim(trim(string) // 'levels:'), rc = status )
+          if (STATUS /= 0) then
+             write (*,*) "MATMATMAT len: ", len
+             write (*,*) "MATMATMAT trim(string): ", trim(string)
+             write (*,*) "MATMATMAT trim(trim(string)) // 'levels:': ", trim(trim(string) // 'levels:')
+             write (*,*) "MATMATMAT STATUS: ", STATUS
+          end if
           VERIFY_(STATUS)
              j = 0
           do i = 1, len
-             call ESMF_ConfigGetAttribute ( config,value=tmpstring ,rc=STATUS)
+             call ESMF_ConfigGetAttribute ( cfg,value=tmpstring ,rc=STATUS)
              VERIFY_(STATUS)
              if( trim(tmpstring) == ',' )  cycle
              j = j + 1
```

My setup is (in case it matters):
```
" for vim-signify
let g:signify_vcs_list = [ 'cvs', 'svn', 'git' ]
let g:signify_disable_by_default    = 0
let g:signify_cursorhold_insert     = 0
let g:signify_cursorhold_normal     = 0
let g:signify_update_on_bufenter    = 0
let g:signify_update_on_focusgained = 0
let g:signify_line_highlight        = 0

nnoremap <leader>gt :SignifyToggle
nnoremap <leader>gh :SignifyToggleHighlight
nnoremap <leader>gr :SignifyRefresh
nnoremap <leader>gd :SignifyDebug

"" hunk jumping
nmap <leader>gj <plug>(signify-next-hunk)
nmap <leader>gk <plug>(signify-prev-hunk)
```

This has worked just fine until that recent PluginUpdate (which was a while ago). Any ideas?

**Comment by mhinz** [comment] 2017-02-10 16:43
1. Some older versions of Vim don't like it when the type of a variable changes.
2. Before we merged the async support a while ago, a diff was a long string with newlines. Now it's a list of strings (because that's what the callbacks offer).

So, an empty diff should be signalized by a `[]` not a `''`. Should be fixed now!

**Comment by mathomp4** [comment] 2017-02-10 16:47
@mhinz Well, on the plus side, it works with Vim 7.4 again. But it doesn't show a gutter with Vim 8.0. Maybe they were built differently? Is there anything in `vim --version` I should look for?

**Comment by mathomp4** [comment] 2017-02-10 16:55
Wait. Now they are in my Vim 8.0 editor. Okay, is there a tmp file somewhere I should nuke? Maybe just rebuild all my plugins?

**Comment by mhinz** [comment] 2017-02-10 18:00
Huh, the plugin itself doesn't use any files for caching, so.. it's hard to say.

Is there any way to reproduce it?

**Comment by mathomp4** [comment] 2017-02-10 18:05
I'll try a few things to see if I can. The main "symptom" right now is that vim 7.4 loads the gutter up almost instantaneously, but vim 8.0 seems to have a lag. 

Now, I am on a head node of a cluster that could get a bit congested, but it does have 128 GB of RAM and the sysops are pretty good at letting users know if they are (accidentally) monopolizing them (he says with experience).

**Comment by jamessan** [comment] 2017-02-10 18:08
There's a little lag with vim 8 because signify runs the actual diff commands asynchronously.

**Comment by mhinz** [comment] 2017-02-10 18:16
Hmm, `:echo b:sy_info.cmd` should show the exact CVS command used.

Is there a significant difference in execution time between running that command manually in the shell and using Sy?

**Comment by jamessan** [comment] 2017-02-10 18:19
It's just a visual difference.  Pre-jobs Sy would run synchronously which would delay the display of the buffer until Sy was done.  Post-jobs, the buffer is loaded and the signs get added once the command completes.

**Comment by mathomp4** [comment] 2017-02-10 19:37
Ah. Okay. I'll try Neovim to see what it's like on my Mac (easier there than on a cluster). I'll keep you informed.

**Comment by mhinz** [comment] 2017-02-16 13:17
Please do this in the signify repo:

```
$ git pull && git checkout origin/vim-close-exit
```

If there's any delay with Vim, which isn't due to the "visual difference" mentioned above, this _could_ help. As far as I see it, it can only improve the async performance for Vim versions before 8.0.50.

**Comment by mathomp4** [comment] 2017-02-16 13:50
Ooh. Detached head! :+1: 

I took this and it does seem to load up differences that already exist pretty fast in Vim 8, though I think mine is only at 8.0.002 (patches 1-2). Should I ask my admins to get 8.0.069?

**Comment by mhinz** [comment] 2017-02-16 14:32
Nope, there is no need to upgrade Vim right now. I merged the commit above into master!

So, is everything working as expected now?

**Comment by mathomp4** [comment] 2017-02-16 19:27
Okay. I re-checked out master and pulled. I think it all is, I just have to get used to the delay with Vim 8 now. Nothing you can do about that, I just have to be patient. :)

**Comment by mhinz** [comment] 2017-02-16 22:39
@mathomp4 If it's fast at updating signs, then there's nothing wrong. If the first writing of the signs (after opening a new buffer) "feels" slow, it's because Sy might test multiple VCS first to find the correct one. But.. it does so concurrently and you can move while it happens, so Sy should be "more responsive" nowadays.

And see `:h g:signify_vcs_list`. It's recommended to set that option to only those VCS you actually expect to use.

Thanks for reporting the original issue. :-)

**Closed by mhinz** 2017-02-16 22:39 UTC
Labels: bug, solved?
