### ISSUE TITLE
vim-signify is slow on Windows

### ISSUE THREAD

**Issue by skywind3000** [mhinz/vim-signify#200] opened 2017-01-10 13:01 UTC
Opening new files on gvim.exe takes me about 2 seconds when I turn vim-signify on.

It appears executing git.exe is very slow.

**Comment by mhinz** [comment] 2017-01-10 13:08
When you do `git diff <file>` manually, is it slow?

**Comment by skywind3000** [comment] 2017-01-10 13:20
In my experience, starting processes on windows is much slower than starting on linux/mac.

and opening new files only get stuck on my windows desktop.

**Comment by mhinz** [comment] 2017-01-10 13:32
Did you try `git diff <file>` manually? I just want to be sure it's the problem. If so, it will be addressed by #201 as well.

**Comment by skywind3000** [comment] 2017-01-10 13:39
No idea about how to time a windows command,
Detecting by my eyes, it is nearly 0.2 seconds to execute a "git diff file"

**Comment by char101** [comment] 2017-01-17 07:12
It's very slow when editing a file not withing a git repository.

**Comment by skywind3000** [comment] 2017-01-17 07:18
could vim-signify just detect mark files like ".git" and ".svn" in the current directory and backward to all its parent directories util to the root of filesystem ? instead of executing svn or git.

**Comment by skywind3000** [comment] 2017-01-17 07:18
just like what CTRL-P does ?

**Comment by char101** [comment] 2017-01-17 07:22
Profiling result when editing a file not inside a git repo

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   1.957792   0.001694  sy#start()
    1   1.928178   0.000117  sy#repo#detect()
    4   1.928002   0.002088  <SNR>81_run()
    1   1.764657   0.000016  sy#repo#get_diff_cvs()
    9   0.124406             whitespace#can_modify()
    1   0.055699   0.000014  sy#repo#get_diff_git()
    1   0.054396   0.000014  sy#repo#get_diff_hg()
    1   0.053308   0.000014  sy#repo#get_diff_svn()
    1   0.005380   0.000348  stay#view#load()
    3   0.004550   0.000080  <SNR>85_doautocmd()
    1   0.003423   0.003306  <SNR>25_LoadFTPlugin()
    1   0.001786   0.000022  <SNR>32_record()
    1   0.001763   0.000183  <SNR>32_addtomrufs()
    1   0.001493             <SNR>28_SynSet()
    1   0.001405   0.000016  sy#disable()
    1   0.001389   0.001120  sy#stop()
    1   0.001196   0.000242  <SNR>32_mergelists()
    1   0.000836   0.000543  ctrlp#mrufiles#cachefile()
    8   0.000651   0.000492  <SNR>34_WinDo()
    9   0.000612             SetStatusLine()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    9              0.124406  whitespace#can_modify()
    1   0.003423   0.003306  <SNR>25_LoadFTPlugin()
    4   1.928002   0.002088  <SNR>81_run()
    1   1.957792   0.001694  sy#start()
    1              0.001493  <SNR>28_SynSet()
    1   0.001389   0.001120  sy#stop()
    9              0.000612  SetStatusLine()
    1              0.000600  <SNR>26_LoadIndent()
    1   0.000836   0.000543  ctrlp#mrufiles#cachefile()
    8   0.000651   0.000492  <SNR>34_WinDo()
    3              0.000475  syntastic#util#fname2buf()
    1   0.000377   0.000360  ctrlp#utils#writecache()
    1   0.005380   0.000348  stay#view#load()
    1   0.001196   0.000242  <SNR>32_mergelists()
    3              0.000237  sy#util#escape()
    1   0.001763   0.000183  <SNR>32_addtomrufs()
    1   0.000180   0.000158  <SNR>87_RestoreSession()
    1   0.000186   0.000130  stay#ispersistent()
   12              0.000117  <SNR>81_replace()
    1   1.928178   0.000117  sy#repo#detect()
```

**Comment by char101** [comment] 2017-01-17 07:26
In my case it is caused by an invalid `cvs.bat` which takes a bit of time to run, after removing it the profile data is

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1   0.200223   0.001961  sy#start()
    1   0.168244   0.000098  sy#repo#detect()
    3   0.168092   0.001506  <SNR>81_run()
    4   0.121160             whitespace#can_modify()
    1   0.060127   0.000020  sy#repo#get_diff_git()
    1   0.055281   0.000016  sy#repo#get_diff_hg()
    1   0.052739   0.000018  sy#repo#get_diff_svn()
    1   0.005684   0.000327  stay#view#load()
    3   0.004864   0.000084  <SNR>85_doautocmd()
    1   0.003352   0.003237  <SNR>25_LoadFTPlugin()
    1   0.001788   0.000023  <SNR>32_record()
    1   0.001765   0.000167  <SNR>32_addtomrufs()
    1   0.001343             <SNR>28_SynSet()
    1   0.001328   0.000017  sy#disable()
    1   0.001312   0.000826  sy#stop()
    1   0.001222   0.000242  <SNR>32_mergelists()
    1   0.000849   0.000557  ctrlp#mrufiles#cachefile()
    8   0.000773   0.000545  <SNR>34_WinDo()
    3   0.000675   0.000063  <SNR>34_UpdateWin()
    1   0.000580   0.000069  <SNR>49_BufEnterHook()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    4              0.121160  whitespace#can_modify()
    1   0.003352   0.003237  <SNR>25_LoadFTPlugin()
    1   0.200223   0.001961  sy#start()
    3   0.168092   0.001506  <SNR>81_run()
    1              0.001343  <SNR>28_SynSet()
    1   0.001312   0.000826  sy#stop()
    1              0.000572  <SNR>26_LoadIndent()
    1   0.000849   0.000557  ctrlp#mrufiles#cachefile()
    8   0.000773   0.000545  <SNR>34_WinDo()
    3              0.000484  syntastic#util#fname2buf()
    1   0.000368   0.000350  ctrlp#utils#writecache()
    1   0.005684   0.000327  stay#view#load()
    4              0.000279  SetStatusLine()
    3              0.000262  sy#util#escape()
    1   0.001222   0.000242  <SNR>32_mergelists()
    1   0.000224   0.000204  <SNR>87_RestoreSession()
    1   0.001765   0.000167  <SNR>32_addtomrufs()
    1   0.000177   0.000124  stay#ispersistent()
    1              0.000122  ctrlp#utils#readfile()
    4              0.000110  <SNR>34_LeaveWin()
```

**Comment by char101** [comment] 2017-01-17 07:27
Profiling a file inside a git repository

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    8   0.191404   0.191142  <SNR>34_WinDo()
    1   0.154623   0.003443  sy#start()
    3   0.144150   0.000076  <SNR>34_UpdateWin()
    4   0.120015             whitespace#can_modify()
    1   0.100773   0.000334  stay#view#load()
    1   0.062094   0.010945  sy#sign#process_diff()
    1   0.060200   0.000053  sy#repo#detect()
    1   0.060147   0.000038  sy#repo#get_diff_git()
    1   0.060109   0.000744  <SNR>86_run()
    3   0.052772   0.000188  <SNR>91_doautocmd()
  220   0.049281   0.048437  <SNR>88_add_sign()
    1   0.047351   0.000022  <SNR>34_UpdateBuf()
    1   0.015049   0.003881  <SNR>28_SynSet()
    1   0.010269   0.008712  <SNR>25_LoadFTPlugin()
    1   0.002472   0.002147  <SNR>26_LoadIndent()
    1   0.001914   0.000022  <SNR>32_record()
    1   0.001892   0.000256  <SNR>32_addtomrufs()
  220   0.001820             <SNR>88_external_sign_present()
    1   0.001265   0.000258  <SNR>32_mergelists()
    1   0.000888   0.000591  ctrlp#mrufiles#cachefile()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    8   0.191404   0.191142  <SNR>34_WinDo()
    4              0.120015  whitespace#can_modify()
  220   0.049281   0.048437  <SNR>88_add_sign()
    1   0.062094   0.010945  sy#sign#process_diff()
    1   0.010269   0.008712  <SNR>25_LoadFTPlugin()
    1   0.015049   0.003881  <SNR>28_SynSet()
    1   0.154623   0.003443  sy#start()
    1   0.002472   0.002147  <SNR>26_LoadIndent()
  220              0.001820  <SNR>88_external_sign_present()
  220              0.000844  sy#sign#get_next_id()
    1   0.060109   0.000744  <SNR>86_run()
    3              0.000725  syntastic#util#fname2buf()
    1   0.000888   0.000591  ctrlp#mrufiles#cachefile()
    1   0.000363   0.000345  ctrlp#utils#writecache()
    1   0.100773   0.000334  stay#view#load()
    4              0.000334  SetStatusLine()
    1   0.000302   0.000281  <SNR>93_RestoreSession()
    1   0.001265   0.000258  <SNR>32_mergelists()
    1   0.001892   0.000256  <SNR>32_addtomrufs()
    1              0.000252  <SNR>23_isAnsible()
```

**Comment by char101** [comment] 2017-01-17 07:28
@skywind3000 Maybe you can check the runtime of each cvs/hg/git/svn diff in your computer. It is possible that one of these command is the cause of the slowness.

**Comment by mhinz** [comment] 2017-01-17 12:10
As a general tip, if there's any option you should set, it would be `:h g:signify_vcs_list`.

@skywind3000 Especially git, from all VCS, should return a `git diff` nearly instantly. Are you working on a remote system maybe? It would be nice to see your [profile data](https://github.com/mhinz/vim-galore/#profiling-at-runtime) as well.

When the async code is ready, I'd like to test all VCS from `g:signify_vcs_list` concurrently, which should speed up detection even more.

@char101 

The first thing I see is that your file has quite some changes. 220x `add_sign()` means a lot of diff processing in VimL and that's probably the slowed part of the plugin itself. (In practice the bottlenecks are almost always slow file access, other plugins etc.)

In the non-git repo case, `g:signify_vcs_list` should help you as well.

In the git repo case, the profile doesn't look too bad. `sy_start()` takes 0.154623 for _everything_ that includes the 220x `add_sign()` etc. You can see that other plugins take just as long or even longer, e.g. the plugins that use `s:WinDo()`, `s:UpdateWin()`, `whitespace#can_modify()`, `stay#view#load()`.

**Comment by mhinz** [comment] 2017-01-18 10:18
@skywind3000 @char101 

Please try out the async branch (`git pull && git checkout async`). I'd like to know how well it works on Windows.

**Comment by char101** [comment] 2017-01-19 04:25
I have tried the async branch. Probably no noticeable difference in speed because the sync version is already fast enough, but I notice that the signs appear after the file has been loaded, which feel _async'y_ 😄 

Profile data for the async branch

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    8   0.195140   0.194885  <SNR>35_WinDo()
    3   0.147392   0.000074  <SNR>35_UpdateWin()
    1   0.120614   0.000061  <SNR>87_callback_exit()
    1   0.120538   0.000040  sy#repo#get_diff_git()
    1   0.120488   0.000035  <SNR>87_get_diff_end()
    1   0.120444   0.004197  sy#set_signs()
    6   0.119419             whitespace#can_modify()
    1   0.114168   0.020502  sy#sign#process_diff()
    1   0.100027   0.000348  stay#view#load()
  220   0.090167   0.088546  <SNR>94_add_sign()
    3   0.051061   0.000178  <SNR>90_doautocmd()
    1   0.047846   0.000024  <SNR>35_UpdateBuf()
    1   0.016458   0.002691  <SNR>29_SynSet()
    1   0.010748   0.009340  <SNR>26_LoadFTPlugin()
    1   0.005676   0.001564  sy#start()
  220   0.003398             <SNR>94_external_sign_present()
    1   0.002775   0.000028  sy#repo#detect()
    1   0.002746   0.002651  sy#repo#get_diff_start()
    1   0.002171   0.000021  <SNR>33_record()
    1   0.002149   0.000276  <SNR>33_addtomrufs()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    8   0.195140   0.194885  <SNR>35_WinDo()
    6              0.119419  whitespace#can_modify()
  220   0.090167   0.088546  <SNR>94_add_sign()
    1   0.114168   0.020502  sy#sign#process_diff()
    1   0.010748   0.009340  <SNR>26_LoadFTPlugin()
    1   0.120444   0.004197  sy#set_signs()
  220              0.003398  <SNR>94_external_sign_present()
    1   0.016458   0.002691  <SNR>29_SynSet()
    1   0.002746   0.002651  sy#repo#get_diff_start()
    1   0.002080   0.001886  <SNR>27_LoadIndent()
  494              0.001778  <SNR>87_callback_stdout_vim()
  220              0.001622  sy#sign#id_next()
    1   0.005676   0.001564  sy#start()
    3              0.000712  syntastic#util#fname2buf()
    1   0.001136   0.000522  ctrlp#mrufiles#cachefile()
    6              0.000503  SetStatusLine()
    1   0.100027   0.000348  stay#view#load()
    1   0.000351   0.000334  ctrlp#utils#writecache()
    1   0.000308   0.000286  <SNR>92_RestoreSession()
    1   0.002149   0.000276  <SNR>33_addtomrufs()
```

**Comment by mhinz** [comment] 2017-01-19 12:40
@char101 Ah, thanks for all the profiling data. I'm glad the async branch had no regressions so far. :-)

There's only so much that "async" (which means using `job_start()` in Vim) can do. It just means that all the shell commands Sy uses, e.g. `git diff ...`, `accurev diff` etc., are run in the background. But their callback handlers do not. So, if the process returns with a diff, the synchronous diff processing starts. It's a [huge loop](https://github.com/mhinz/vim-signify/blob/master/autoload/sy/sign.vim#L53-L191) that does a lot of things and VimL isn't known to be super performant.

Nevertheless it should only be noticable if you have _a lot_ of signs. If that happens, you have another problem. Vim itself isn't very smart about setting many signs at the same time. Hopefully that will improved in the future.

Putting it in a nutshell.. the async branch should have these concrete advantages:

1. If your system is under heavy load or you work on remote file systems, you can still move whill the shell command runs in the background.
2. The should be no noticable delay when opening a new file. We already do some guessing, e.g., if `dir/foo` is controlled by git, it's likely that `dir/bar` is controlled by git as well, so we test for git first etc. But now all the shell commands that test for the used VCS run asynchronously. So, in theory, if each shell command would take 0.2s and we test for 5 of them, it would only need a bit above 0.2s to get a result instead of 1s.
3. If used on Windows, you shouldn't see `cmd.exe` flashing up anymore. (That alone should be pretty cool for Win users. I'd go crazy when something pops every time I save.)

So, **2.** should address this issue here. If the shell process itself is slow, there's nothing I can do about it. But it doesn't block anymore, so it should be fine. :-)

**Comment by char101** [comment] 2017-01-20 07:04
I can't verify **No. 3** since I compiled Vim myself and have few patches managed with mercurial mq, one of which to hide the console window.

But looking at current vim source it seems that the `system` command can be made not to show the console window by setting the `noshelltemp` option.

**Comment by mhinz** [comment] 2017-01-20 08:57
I think the problem is that `'shell'` is set to `cmd.exe` (the default), which is used by `:!` and `system()`. So every time a shell command is used, a `cmd.exe` will be started, the command will be executed, `cmd.exe` closes.

**Comment by char101** [comment] 2017-01-20 09:07
Running via cmd.exe is fine (it enable shell commands and operators). What is required to make it hidden is to set `SW_HIDE` when calling [CreateProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx). It was set when `shelltemp` is off (calls `mch_system_piped`) but not when `shelltemp` is on (`mch_system_classic` is called instead).

**Comment by mhinz** [comment] 2017-01-22 14:08
@skywind3000 Okay, I merged the async branch into master.

1) Even if it's not as important as before the PR patch anymore, set `g:startify_vcs_list`.
2) Make sure that manually runnning `git diff` isn't slow already. (`:SignifyDebug` shows you the exact command run.) If it is, there's nothing the plugin can do about it.

If you considered the two points above and still have performance issues, please reopen this issue and we'll figure it out.

**Closed by mhinz** 2017-01-22 14:08 UTC
Labels: performance, windows
