### ISSUE TITLE
Windows: issue with soft links

### ISSUE THREAD

**Issue by zdm** [mhinz/vim-signify#299] opened 2019-06-21 15:10 UTC
Starting from vim patch 1417 signify not working under windows.

```
patch 8.1.1417: MS-Windows: resolve() does not resolve all components…
… of path

Problem:    MS-Windows: resolve() does not resolve all components of the path.
            (David Briscoe)
Solution:   Do not bail out for a reparse point. (Yasuhiro Matsumoto,
            closes #4211, closes #4447)
```

**Comment by mhinz** [comment] 2019-07-10 12:34
Is this still a problem with the latest Vim? As far as I understand it, it's `resolve()` being broken on Windows and there is nothing that I can do about it.

**Comment by zdm** [comment] 2019-07-10 12:42
Yes, the problem is exists in the vim after patch 1417.
I think, you need to update code to make it compatible with the changes
in that patch.
I can help to debug and test.

**Comment by mhinz** [comment] 2019-07-10 14:03
> you need to update code to make it compatible with the changes

What is that supposed to mean? Either I use `resolve()` or I don't. And if `resolve()` isn't working for you on Windows, it must be a bug in Vim not this plugin.

In https://github.com/mhinz/vim-signify/issues/298#issuecomment-497573753 you said that 8.1.1417 caused the problems, but in a later comment, https://github.com/mhinz/vim-signify/issues/298#issuecomment-499528170, you said that it would work now. Confusing!

Disclaimer: I have no idea what a reparse point is.

@chrisbra Am I missing something here?

**Comment by zdm** [comment] 2019-07-10 14:06
Seems, that  was my mistake In #298 (comment).
It stop work after patch 1417.

**Comment by mhinz** [comment] 2019-07-10 14:26
Okay. If it's really caused by patch 1417, then it must be related to `resolve()`. That function is only used once in the plugin.

Does it help if you change https://github.com/mhinz/vim-signify/blob/master/autoload/sy.vim#L15 to `let sy_path = expand('%:p')`?

Is the path still `d:\work\fbadbot\TODO.txt`? Is that a normal path? Not a link or anything?

**Comment by zdm** [comment] 2019-07-10 14:32
1. Yes, this fixed the problem.

2. d:\work is a symbolic link to directory;

**Comment by mhinz** [comment] 2019-07-10 14:35
So.. when do I know when to use `resolve()` on Windows and when I should avoid it? I still think it's a Vim problem and should be reported to the vim_dev mailing list.

Just out of interest: When `d:\work\fbadbot\TODO.txt` is opened in Vim, what is the result of `:echo resolve(expand('%:p'))`? Empty string?

**Comment by zdm** [comment] 2019-07-10 14:38
no, not empty, it returns path, with resolved symlink.

**Comment by mhinz** [comment] 2019-07-10 14:39
Did you really test the _latest_ Vim patch? https://github.com/vim/vim/commit/4a792c87b9a643a949ee36106a2f7e971dc633f8 sounds like it resolves your issue.

**Comment by zdm** [comment] 2019-07-10 14:43
Yes, i just installed fresh vim, 10 minutes ago.
Signify is not working without your fix.

**Comment by mhinz** [comment] 2019-07-10 14:49
What does the resolved path look like?

**Comment by zdm** [comment] 2019-07-10 14:52
filename: d:\work\1.txt
resolved: d:\gdrive\work\1.txt

**Comment by mhinz** [comment] 2019-07-10 14:56
What's the output of:

```
:echo system('hg diff --color=never --config aliases.diff= --nodates -U0 -- "d:\gdrive\work\1.txt"')
```

**Comment by zdm** [comment] 2019-07-10 15:00
normal hg diff

**Comment by zdm** [comment] 2019-07-10 15:03
yes, process 0 fail

**Comment by mhinz** [comment] 2019-07-10 15:05
So.. maybe https://github.com/mhinz/vim-signify/commit/ac23bd95d5fe0c7a7bf4a331e9d37eb72697c46e, which was supposed to fix this problem, didn't help at all?

Can you `git checkout c3f26e4` in the git repo of this plugin and see if it works?

**Comment by mhinz** [comment] 2019-07-10 15:17
And make sure that `git checkout ac23bd9` (should be equal to `origin/master`) isn't work either.

If both commits don't work, I'm seriously out of ideas. I simply can't reproduce it.

**Comment by mhinz** [comment] 2019-07-10 15:22
And please mention the exact Vim version you're using now.

**Comment by zdm** [comment] 2019-07-10 16:16
I checked out c3f26e4 - nothing was changed, it still not working.
Tested on latest vim 1658

**Comment by mhinz** [comment] 2019-07-10 16:55
Okay, when both commits don't work, I'm out of ideas. I have no idea if it can even be fixed from the plugin or if `resolve()` is still broken. And obviously I can't just leave `resolve()` away.

@jamessan Any idea what could be wrong here?

**Comment by chrisbra** [comment] 2019-07-10 17:03
Sorry I am currently away.

Please try to reproduce to a minimal example that fails with vim and open an issue there. Seems like a patch that had regressed.

**Comment by zdm** [comment] 2019-07-10 17:05
The problem is that:
- in vim before 1417 echo resolve(expand('%:p')) - return unresolved
path, this is incorrect;
- in vim after 1417 - resolved, that is correct behavior;

If, for eample, we started vim in d:\work, that is symlink to the
d:\gdrive and you run "hg diff d:\gdrive\1.txt" - it will not work,
because you started mercurial in "d:\work" and check file in
"d:\gdrive". You should use resolve or unresolved paths, do not mix
them. I hope you understand my Englis.

**Comment by mhinz** [comment] 2019-07-10 17:43
I think I understand what you mean, but as far as I see, all paths should be resolved.

Right at the start, we `resolve()` right away: https://github.com/mhinz/vim-signify/blob/master/autoload/sy.vim#L15

I use different paths for different cases, but they all rely on the already resolved `sy_path`: https://github.com/mhinz/vim-signify/blob/ac23bd95d5fe0c7a7bf4a331e9d37eb72697c46e/autoload/sy.vim#L42-L44

(You can check `:echo b:sy.info` which should show the resolved paths.)

I'm currently updating my Windows VM to 1903, which takes ages... afterwards I'll play around with soft links. (You used `mklink /D` for linking, right?)

**Comment by mhinz** [comment] 2019-07-12 12:52
Soft and hard links (junctions) work fine here.

E.g. I created a soft link (`mklink /D`) `C:\Users\Marco\link` from `C:\Users\Marco\repo`. Then I start Vim, then `:set verbose=1`, then `:e ~\link\file.txt`. I get verbose messages, click any key, and then let me show all messages again via `:messages`:

```
[sy] Register new file: C:\Users\Marco\repo\file.txt
[sy:hg] get_diff_start()
[sy:hg] CMD: 'cmd.exe /c ( hg diff --color=never --config aliases.diff= --nodates -U0 -- "C:\Users\Marco\repo\file.txt" )'
[sy:hg] CMD DIR:  C:\Users\Marco\repo
[sy:hg] CMD ORIG: C:\Users\Marco
[sy:hg] job_exit()
[sy:hg] get_diff_hg()
[sy:hg] get_diff_end()
[sy:hg] set_signs()
[sy:hg] Signs updated.
```

So, all used paths are the resolved ones to `~\repo` and not `~\link`.

**Comment by zdm** [comment] 2019-07-12 13:10
It works for you with the latest vim?

**Comment by mhinz** [comment] 2019-07-12 15:44
From 2 days ago: 8.1.1657

**Comment by zdm** [comment] 2019-07-12 15:52
I just tested with 1657 - it is not working for me ;-(

**Comment by zdm** [comment] 2019-07-12 16:06
How I can check, what command is executed to get diff and from what directory it is started?

**Comment by mhinz** [comment] 2019-07-12 17:19
As described in https://github.com/mhinz/vim-signify/issues/299#issuecomment-510875031

**Comment by zdm** [comment] 2019-07-12 17:38
Why I get this?
```
[sy] Skip file: C:\gdrive\projects\pcore-lib\arbitrator\TODO.txt 
```

**Comment by mhinz** [comment] 2019-07-12 17:52
Can be several things:

- You're in diff mode. `:echo &diff` should show 0.
- The file is not readable for some reason. `:echo filereadable(resolve(expand('%:p')))` should return 1.
- `g:signify_skip_filetype` is set in your vimrc and matches the file's filetype.
- `g:signify_skip_filename` is set in your vimrc and matches the filename.
- `g:signify_skip_filename_pattern` is set in your vimrc and matches the filename.

**Comment by zdm** [comment] 2019-07-12 18:00
1. I am not in diff mode;
2. return 0 - file is not readable, but why? I opened it in vim and edit
without problems;

**Comment by zdm** [comment] 2019-07-12 18:03
If i run ```echo filereadable``` in the original dir - it returns 1;
If in symlinked dir - 0;

**Comment by zdm** [comment] 2019-07-12 18:06
I found the problem
```
echo resolve(expand('%:p'))
```
returns in valid path. It should return ```D:\...```, but it returns ```C:\...```

**Comment by mhinz** [comment] 2019-07-12 18:14
Oh, wow. 

So, it resolves the actual path, but keeps the `C:\` from the link. That sounds very much like a Vim bug. :-)

And returns `C:\` although the original file _and_ the link are both under `D:\`, right?

**Comment by zdm** [comment] 2019-07-12 18:17
Yes, both files, original and linked, are in D:, and vim started in D:, but vimrc located in home dir, that is in C:.

**Comment by mhinz** [comment] 2019-07-12 18:20
Will you create a bug report for it? https://github.com/vim/vim/issues/new?labels=&template=bug_report.md&title=

You should mention:

- your Vim version
- the path of the original file
- the path of the link
- how you created the link (probably `mklink /D`, I guess)
- that `:echo filereadable(resolve(expand('%:p')))` returns the wrong path

So, any steps people need to know to reproduce the issue.

**Comment by zdm** [comment] 2019-07-12 18:21
yes, will do

**Comment by mhinz** [comment] 2019-07-12 18:22
Perfect! Please link that issue in here afterwards, so other people having the same issue have a reference.

**Comment by zdm** [comment] 2019-07-12 19:02
Here are steps for reproduce:
```
mkdir d:\111
mklink /D "d:\222" "d:\111"
cd /D "d:\222"
touch 1.txt (or create d:\222\1.txt somehow, if you don't have touch command)
vim 1.txt
:echo resolve(expand('%:p'))
```

Could you, please, confir, that resolve() return c:\... on your system?

**Comment by mhinz** [comment] 2019-07-12 19:50
Hmm, I can't reproduce it with Vim 8.1.1657 (and according to the commit messages up to 8.1.1673 nothing changed `resolve()` afterwards).

I'm using Virtualbox, so C: is my main drive and D: the CD drive with the VirtualBox additions. I added a new drive E: and followed your steps using that drive.

But `:echo expand('%:p')` returns `e:\222\1.txt` (lowercase `e:`) and `:echo resolve(expand('%:p'))` returns `E:\111\1.txt` (resolved path with uppercase `E:`).

**Comment by zdm** [comment] 2019-07-12 20:17
file 1.txt should be created before you open it in vim, otherwise
everything works.

**Comment by mhinz** [comment] 2019-07-12 20:33
Yup, did that.

Maybe it doesn't happen with regular drives and just with virtual drives like gdrive?

Anyway, I would just report it anyway, since you can repeat it every time and I'm no Windows person. More eyes will find the real issue quicker. :)

**Comment by mhinz** [comment] 2019-08-06 21:55
Fixed as of https://github.com/vim/vim/commit/3f9bdeb2a521a408c04fd9584a752845b3accbbd

**Closed by mhinz** 2019-08-06 21:55 UTC
Labels: vim-bug, windows
