### ISSUE TITLE
Error when running `:SignifyHunkDiff`

### ISSUE THREAD

**Issue by kuntau** [mhinz/vim-signify#342] opened 2020-05-16 19:29 UTC
```
Error detected while processing function <SNR>117_callback_nvim_exit[1]..<SNR>117_handle_diff[31]..<SNR>117_diff_hunk[8]..sy#util#popup_create:
line   32:
E5555: API call: Option 'foldcolumn' requires a string value
```

The error I got when running `:SignifyHunkDiff` command on hunks

**Comment by jamessan** [comment] 2020-05-16 19:38
Duplicate of #340

**Comment by kuntau** [comment] 2020-05-16 19:44
Ah... Sorry. I saw that one but I thought it's a different issue since the following error regarding `foldcolumn` and related to mhinz/vim-signify/pull/334

**Comment by jamessan** [comment] 2020-05-16 20:09
Oops, I read too quickly. You're right, this is different.

**Closed** 2020-05-16 20:16 UTC
