### ISSUE TITLE
No diff markers when toggling signcolumn using autocmd

### ISSUE THREAD

**Issue by lakshayg** [mhinz/vim-signify#348] opened 2020-06-17 06:29 UTC
The commit c3d450eb5f5e76d99d23b10493d4e08c5bb1ae71 seems to have introduced some issue in the plugin. I have the following in my vimrc (this is the whole vimrc, there's nothing besides this)

```
call plug#begin()
Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-signify'
call plug#end()

set updatetime=750

augroup Vimrc
  autocmd!
  autocmd OptionSet diff
        \ if &diff
        \ |   setlocal signcolumn=no
        \ | else
        \ |   setlocal signcolumn=auto
        \ | endif
augroup END
```

The augroup is the important part. This hides the signcolumn when I'm viewing a diff. When leaving the diff mode, it brings back the sign column. Until the latest commit, this worked as expected but since updating, vim-signify does not display any markers after leaving the diff mode, i.e

- Open a modified file (diff markers are visible, expected)
- Do `:Gdiffsplit` (vim-fugitive) (diff markers hidden, expected)
- Close the diff buffer with `:q` (signcolumn is enabled but diff markers are not shown, *unexpected*)

The markers appear again if I do `SignifyRefresh` or `:e` which makes me think that this problem might be related to #347 

I'm using neovim 0.4.3 on macOS

**Comment by jamessan** [comment] 2020-06-20 03:27
>     * Do `:Gdiffsplit` (vim-fugitive) (diff markers hidden, expected)

I think the relevant part here is actually the diff buffer, not the autocmd.  That's essentially the same as what #347 is doing except via fugitive.  I'm going to close this as a duplicate of #347.

**Closed by jamessan** 2020-06-20 03:27 UTC

**Comment by jamessan** [comment] 2020-06-20 03:29
Duplicate of #347
